version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - SERVICE_CONTAINER_ID=${SERVICE_CONTAINER_ID}
    depends_on:
      - service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  service:
    build:
      context: ./faum
      dockerfile: Dockerfile
      network: host
    container_name: service
    volumes:
      - /c/users/Tobi/Desktop/volumen:/app/fotos
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVICE_CONTAINER_ID=${HOSTNAME} # Esto expone el ID al backend
    dns:
      - 8.8.8.8
networks:
  app-network:
    driver: bridge
